# Generated by Django 4.2.2 on 2023-07-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_genre', models.CharField(blank='', max_length=30, verbose_name='Genero')),
                ('n_rating', models.IntegerField(verbose_name='Valoración')),
                ('t_description', models.CharField(blank='', max_length=500, verbose_name='Descripción')),
                ('t_title', models.CharField(blank='', max_length=30, verbose_name='Titulo')),
                ('n_duration', models.IntegerField(verbose_name='Duración')),
            ],
        ),
    ]
