version: '3.7'
services:
  patrones_front:
    image: patrones-front:1.0
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == juferoga]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.front.entrypoints=websecure"
        - "traefik.http.routers.front.rule=Host(`patrones.juferoga.live`)"
        - "traefik.http.routers.front.service=front"
        - "traefik.http.services.front.loadbalancer.server.port=80"
networks:
    proxy:
      external: true
