# Generated by Django 4.2.2 on 2023-07-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_direction', models.CharField(blank='', max_length=30, verbose_name='Dirección del cinema')),
                ('t_name', models.CharField(max_length=255, verbose_name='Nombre del cinema')),
            ],
        ),
    ]
