# Generated by Django 4.2.2 on 2023-07-01 20:34

import apps.authuser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('n_points', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Cliente',
            },
            bases=('authuser.user',),
            managers=[
                ('objects', apps.authuser.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('n_salary', models.DecimalField(decimal_places=2, default=1000000, max_digits=7)),
                ('d_start_contract', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('d_end_contract', models.DateTimeField(blank=True, null=True)),
                ('t_rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Empleado'), (3, 'Cliente')], default=2)),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleado',
            },
            bases=('authuser.user',),
            managers=[
                ('objects', apps.authuser.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='n_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='n_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='t_id',
            field=models.IntegerField(choices=[(1, 'Cédula de ciudadanía'), (2, 'Tarjeta de identidad'), (3, 'Cédula de extranjería')], default=1),
        ),
    ]
