# Generated by Django 4.2.2 on 2023-07-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        ('authuser', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fk_cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
    ]
