# Generated by Django 4.2.2 on 2023-07-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_employee_fk_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='n_salary',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
    ]
