# Generated by Django 4.2.2 on 2023-07-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_alter_employee_n_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='t_rol',
        ),
        migrations.AddField(
            model_name='user',
            name='t_rol',
            field=models.IntegerField(choices=[(0, 'Administrador Administrador'), (1, 'Administrador'), (2, 'Empleado'), (3, 'Cliente')], default=3),
        ),
    ]
