# Generated by Django 4.2.2 on 2023-07-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_date', models.DateField()),
                ('d_start_time', models.TimeField()),
                ('d_end_time', models.TimeField()),
                ('fk_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
            ],
        ),
    ]
