# Generated by Django 4.2.2 on 2023-07-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_function_fk_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='fk_theater',
        ),
    ]
