# Generated by Django 4.2.2 on 2023-07-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='fk_product',
            field=models.ManyToManyField(null=True, related_name='producto_pedido', to='product.product'),
        ),
    ]
