# Generated by Django 4.2.2 on 2023-07-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_snack_ticket'),
        ('purchase', '0002_alter_purchase_fk_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='fk_product',
            field=models.ManyToManyField(related_name='producto_pedido', to='product.product'),
        ),
    ]
