# Generated by Django 4.2.2 on 2023-07-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_state', models.BooleanField(default=True)),
            ],
        ),
    ]
