# Generated by Django 4.2.2 on 2023-07-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='fk_cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
    ]
