# Generated by Django 4.2.2 on 2023-07-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(default='Juferoga :v', max_length=100)),
                ('t_description', models.CharField(blank=True, max_length=255, null=True)),
                ('n_price', models.DecimalField(decimal_places=2, default=20000, max_digits=50)),
            ],
        ),
    ]
