# Generated by Django 4.2.2 on 2023-07-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_snack_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='b_state',
            field=models.BooleanField(default=False),
        ),
    ]
