# Generated by Django 4.2.2 on 2023-07-02 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_ticket_b_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_type', models.CharField(max_length=255)),
                ('b_state', models.BooleanField(default=False)),
                ('fk_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ticket')),
            ],
        ),
    ]
