# Generated by Django 4.2.2 on 2023-07-02 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_theater_fk_cinema'),
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='fk_theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theater.theater'),
        ),
    ]
