# Generated by Django 4.2.2 on 2023-07-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
        ('seat', '0002_seat_fk_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='fk_theater',
        ),
        migrations.AddField(
            model_name='seat',
            name='fk_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
    ]
